version: "3.3"

networks:
  stg-server_stg-services:
    external: true

services:
  backend-dev-services-jobelle:
    container_name: stg-services-app-jobelle
    build:
      context: ./
      dockerfile: ./web-app/Dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    volumes:
      - ./web-app/master:/var/www/html:delegated
    restart: unless-stopped
    networks:
      stg-server_stg-services:
        ipv4_address: 172.22.0.23
        
  web-server-jobelle:
    container_name: stg-services-nginx-jobelle
    build:
      context: ./
      dockerfile: ./nginx/Dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    ports:
      - "8089:80"
    volumes:
      - ./web-app/master:/var/www/html:delegated
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend-dev-services-jobelle

    restart: unless-stopped
    networks:
      stg-server_stg-services:
        ipv4_address: 172.22.0.24
