version: "3.3"

networks:
  stg-server_central-services:
    external: true

services:
  backend-dev-services:
    container_name: stg-services-app
    build:
      context: ./
      dockerfile: ./web-app/Dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    volumes:
      - ./web-app/master:/var/www/html:delegated
    restart: unless-stopped
    networks:
      stg-server_central-services:
        ipv4_address: 172.25.0.10
        
  web-server:
    container_name: stg-services-nginx
    build:
      context: ./
      dockerfile: ./nginx/Dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    ports:
      - "8089:80"
    volumes:
      - ./web-app/master:/var/www/html:delegated
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend-dev-services

    restart: unless-stopped
    networks:
      stg-server_central-services:
        ipv4_address: 172.25.0.11